Add `NoSuchMethodError` section to troubleshooting guide (#2300)
* Mention exclusion of fields in troubleshooting guide

* Add `NoSuchMethodError` section to troubleshooting guide

* Add missing word

(cherry picked from commit d7fb0e4a3162c72463821753d96d4a75a3b705a9)